## Association Rule

In [3]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.23.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\windows\new folder\lib\site-packages (from mlxtend) (1.11.4)
Requirement already satisfied: numpy>=1.16.2 in c:\windows\new folder\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\windows\new folder\lib\site-packages (from mlxtend) (2.1.4)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\windows\new folder\lib\site-packages (from mlxtend) (1.2.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\windows\new folder\lib\site-packages (from mlxtend) (3.8.0)
Requirement already satisfied: joblib>=0.13.2 in c:\windows\new folder\lib\site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\windows\new folder\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\windows\new folder\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\windows\new folder\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\windows\new folder\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\windows\new folder\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.1-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
    --------------------------------------- 0.0/1.4 MB 325.1 kB/s eta 0:00:05
   - -------------------------------------- 0.0/1.4 MB 326.8 kB/s eta 0:00:05
   - -------------------------------------- 0.0/1.4 MB 326.8 kB/s eta 0:00:05
   - -------------------------------------- 0.1/1.4 MB 251.0 kB/s eta 0:00:06
   --- ------------------------------------ 0.1/1.4 MB 423.5 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/1.4 MB 482.7 kB/s eta 0:00:03
   ----- ---------------------------------- 0.2/1.4 MB 540.4 kB/s eta 0:00:03
   ------- -------------------------------- 0.3/1.4 MB 603.8 kB/s eta 0:00:02
   ------- -------------------------------- 0.3/1.4 MB 609.0 kB/s eta 0:00:02
   --------- ------------------------------ 0.3/1.4 MB 675.8 kB/s eta 0:00:02
   ---------- ----------------------------- 0.4/1.4 MB 694.6 kB/s eta 0:00:02
   ---------- ----------------------------- 0.4/1.4 MB 654.4 kB/s eta 0:00:02
   ----------- ---------------------------- 0.4/1.4 MB 671.5 kB/s eta 0:00:02
   ----------- ---------------------------- 0.4/1.4 MB 639.0 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.4 MB 668.7 kB/s eta 0:00:02
   -------------- ------------------------- 0.5/1.4 MB 667.8 kB/s eta 0:00:02
   --------------- ------------------------ 0.6/1.4 MB 667.0 kB/s eta 0:00:02
   ---------------- ----------------------- 0.6/1.4 MB 667.1 kB/s eta 0:00:02
   ----------------- ---------------------- 0.6/1.4 MB 688.6 kB/s eta 0:00:02
   ------------------ --------------------- 0.7/1.4 MB 686.9 kB/s eta 0:00:02
   -------------------- ------------------- 0.7/1.4 MB 705.5 kB/s eta 0:00:02
   -------------------- ------------------- 0.7/1.4 MB 704.2 kB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 702.0 kB/s eta 0:00:01
   ---------------------- ----------------- 0.8/1.4 MB 708.0 kB/s eta 0:00:01
   ----------------------- ---------------- 0.8/1.4 MB 688.9 kB/s eta 0:00:01
   ------------------------ --------------- 0.9/1.4 MB 687.5 kB/s eta 0:00:01
   ------------------------- -------------- 0.9/1.4 MB 694.8 kB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.4 MB 716.6 kB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.4 MB 707.8 kB/s eta 0:00:01
   ---------------------------- ----------- 1.0/1.4 MB 705.0 kB/s eta 0:00:01
   ----------------------------- ---------- 1.1/1.4 MB 703.4 kB/s eta 0:00:01
   ----------------------------- ---------- 1.1/1.4 MB 695.0 kB/s eta 0:00:01
   ------------------------------- -------- 1.1/1.4 MB 706.6 kB/s eta 0:00:01
   -------------------------------- ------- 1.2/1.4 MB 712.1 kB/s eta 0:00:01
   --------------------------------- ------ 1.2/1.4 MB 716.6 kB/s eta 0:00:01
   --------------------------------- ------ 1.2/1.4 MB 715.8 kB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.4 MB 713.2 kB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.4 MB 706.0 kB/s eta 0:00:01
   ------------------------------------ --- 1.3/1.4 MB 704.7 kB/s eta 0:00:01
   ------------------------------------- -- 1.4/1.4 MB 703.4 kB/s eta 0:00:01
   -------------------------------------- - 1.4/1.4 MB 707.3 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.7 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 711.1 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 449.2 kB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.1

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from mlxtend.frequent_patterns import association_rules,apriori

In [ ]:
# Read the Data

In [2]:
df=pd.read_excel(r'C:\Users\sanket\Desktop\DS ASSIGNMENT\Association Rules\Association Rules\Online retail.xlsx')
df

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [3]:
df.dtypes

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    object
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                           --------------  -----
 0   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil  7500 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

### Data Preprocessing

In [ ]:
# Find duplicate value

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7495    False
7496    False
7497     True
7498     True
7499    False
Length: 7500, dtype: bool

In [6]:
df.duplicated().sum()

2325

In [7]:
df.shape

(7500, 1)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

0

In [10]:
df.shape

(5175, 1)

In [ ]:
# find missing value

In [11]:
df.isna()

      shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                                 False
1                                                 False
2                                                 False
3                                                 False
4                                                 False
...                                                 ...
7492                                              False
7493                                              False
7495                                              False
7496                                              False
7499                                              False

[5175 rows x 1 columns]

In [12]:
df.isna().sum()

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

### Association Rule Mining

In [13]:
# Split the product
def txt_split(txt):
    return txt.split(',')

In [14]:
df= df['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'].apply(txt_split)
df

0                              [burgers, meatballs, eggs]
1                                               [chutney]
2                                       [turkey, avocado]
3       [mineral water, milk, energy bar, whole wheat ...
4                                        [low fat yogurt]
                              ...
7492    [burgers, salmon, pancakes, french fries, froz...
7493    [turkey, burgers, dessert wine, shrimp, pasta,...
7495                    [butter, light mayo, fresh bread]
7496    [burgers, frozen vegetables, eggs, french frie...
7499    [eggs, frozen smoothie, yogurt cake, low fat y...
Name: shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil, Length: 5175, dtype: object

In [15]:
from mlxtend.preprocessing import TransactionEncoder

In [16]:
te = TransactionEncoder()
encoded_df = te.fit_transform(df)

In [18]:
encoded_df

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]])

In [19]:
te.columns_

[' asparagus',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [20]:
data = pd.DataFrame(encoded_df, columns=te.columns_)
data

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5170,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5171,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
5172,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [21]:
data.replace([True,False],[1,0], inplace=True)

In [22]:
data

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5170,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5171,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
5172,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5173,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5174,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [23]:
data.shape

(5175, 120)

In [24]:
scores = apriori(data,min_support = 0.01,use_colnames=True)
scores

C:\Users\sanket\AppData\Roaming\Python\Python311\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                               itemsets
0    0.029179                              (almonds)
1    0.011014                    (antioxydant juice)
2    0.045797                              (avocado)
3    0.012560                                (bacon)
4    0.015459                       (barbecue sauce)
..        ...                                    ...
431  0.014686  (spaghetti, mineral water, olive oil)
432  0.016618   (spaghetti, mineral water, pancakes)
433  0.012367     (spaghetti, mineral water, shrimp)
434  0.010821       (spaghetti, mineral water, soup)
435  0.013527   (spaghetti, mineral water, tomatoes)

[436 rows x 2 columns]

In [26]:
rules = association_rules(scores,metric="confidence", min_threshold=0.2)

In [27]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(almonds),(mineral water),0.029179,0.299710,0.010821,0.370861,1.237399,0.002076,1.113092,0.197619
1,(avocado),(chocolate),0.045797,0.205217,0.010242,0.223629,1.089716,0.000843,1.023715,0.086281
2,(avocado),(french fries),0.045797,0.192657,0.011594,0.253165,1.314069,0.002771,1.081019,0.250476
3,(avocado),(milk),0.045797,0.170048,0.010821,0.236287,1.389528,0.003034,1.086732,0.293786
4,(avocado),(mineral water),0.045797,0.299710,0.015845,0.345992,1.154421,0.002120,1.070766,0.140185
...,...,...,...,...,...,...,...,...,...,...
350,"(mineral water, shrimp)",(spaghetti),0.033430,0.229565,0.012367,0.369942,1.611491,0.004693,1.222800,0.392580
351,"(spaghetti, soup)",(mineral water),0.020676,0.299710,0.010821,0.523364,1.746235,0.004624,1.469236,0.436362
352,"(mineral water, soup)",(spaghetti),0.033430,0.229565,0.010821,0.323699,1.410054,0.003147,1.139190,0.300865
353,"(spaghetti, tomatoes)",(mineral water),0.029952,0.299710,0.013527,0.451613,1.506832,0.004550,1.276999,0.346742
354,"(mineral water, tomatoes)",(spaghetti),0.034589,0.229565,0.013527,0.391061,1.703487,0.005586,1.265209,0.427765

In [28]:
rules.sort_values(by = 'lift', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
176,(whole wheat pasta),(olive oil),0.040580,0.087536,0.011014,0.271429,3.100757,0.007462,1.252401,0.706154
126,(herb & pepper),(ground beef),0.066473,0.135845,0.022802,0.343023,2.525100,0.013772,1.315350,0.646983
313,"(mineral water, shrimp)",(frozen vegetables),0.033430,0.129855,0.010435,0.312139,2.403747,0.006094,1.265001,0.604181
304,"(spaghetti, frozen vegetables)",(ground beef),0.039034,0.135845,0.012560,0.321782,2.368738,0.007258,1.274155,0.601306
342,"(spaghetti, milk)",(olive oil),0.050048,0.087536,0.010242,0.204633,2.337697,0.005861,1.147224,0.602377
...,...,...,...,...,...,...,...,...,...,...
103,(french fries),(spaghetti),0.192657,0.229565,0.039807,0.206620,0.900049,-0.004421,0.971079,-0.120919
222,"(french fries, chocolate)",(mineral water),0.045990,0.299710,0.012367,0.268908,0.897225,-0.001417,0.957868,-0.107198
123,(green tea),(mineral water),0.169082,0.299710,0.043092,0.254857,0.850345,-0.007584,0.939806,-0.174785
101,(french fries),(mineral water),0.192657,0.299710,0.047923,0.248746,0.829956,-0.009819,0.932162,-0.202408
270,"(french fries, eggs)",(mineral water),0.046377,0.299710,0.010048,0.216667,0.722921,-0.003851,0.893987,-0.286691